### ISSUE TITLE
Error in pagination widget since update 1.3.0

### ISSUE THREAD

**Issue by ssuijkerbuijk** [mendixlabs/list-view-controls#35]
Receiving the following error after updating list view controls from 1.2.3 to 1.3.0. 

Browser console: 
`TypeError: t is not a function
    at Object.<anonymous> (mxui.js?636809834107979290:51)
    at o (mxui.js?636809834107979290:20)
    at Object.t.exports.collect (mxui.js?636809834107979290:20)
    at Object.collect (mxui.js?636809834107979290:31)
    at Object._loadListItems (mxui.js?636809834107979290:51)
    at mxui.js?636809834107979290:51
    at o (mxui.js?636809834107979290:20)
    at Object.t.exports.collect (mxui.js?636809834107979290:20)
    at Object.t.exports.ready (mxui.js?636809834107979290:31)
    at Object._renderData (mxui.js?636809834107979290:51)
(anonymous) @ mxui.js?636809834107979290:74
(anonymous) @ mxui.js?636809834107979290:74
t.log @ mxui.js?636809834107979290:74
t.error @ mxui.js?636809834107979290:74
(anonymous) @ mxui.js?636809834107979290:74`

Mendix console:
`t is not a function TypeError: t is not a function
    at Object.<anonymous> (http://localhost:8080/mxclientsystem/mxui/mxui.js?636809834107979290:51:177958)
    at o (http://localhost:8080/mxclientsystem/mxui/mxui.js?636809834107979290:20:27662)
    at Object.t.exports.collect (http://localhost:8080/mxclientsystem/mxui/mxui.js?636809834107979290:20:27843)
    at Object.collect (http://localhost:8080/mxclientsystem/mxui/mxui.js?636809834107979290:31:15850)
    at Object._loadListItems (http://localhost:8080/mxclientsystem/mxui/mxui.js?636809834107979290:51:178846)
    at http://localhost:8080/mxclientsystem/mxui/mxui.js?636809834107979290:51:177605
    at o (http://localhost:8080/mxclientsystem/mxui/mxui.js?636809834107979290:20:27662)
    at Object.t.exports.collect (http://localhost:8080/mxclientsystem/mxui/mxui.js?636809834107979290:20:27843)
    at Object.t.exports.ready (http://localhost:8080/mxclientsystem/mxui/mxui.js?636809834107979290:31:60189)
    at Object._renderData (http://localhost:8080/mxclientsystem/mxui/mxui.js?636809834107979290:51:177532)`

**Comment by ssuijkerbuijk** [comment]
Mendix version 7.18.1

**Comment by ssuijkerbuijk** [comment]
[ListViewControlsTEST.zip](https://github.com/mendixlabs/list-view-controls/files/2724299/ListViewControlsTEST.zip)

Looks like the error is in the pagination widget

**Comment by Andries-Smit** [comment]
thanks

**Comment by jobvs** [comment]
Unfortunately version 1.3.0 is only compatible with Mendix 7.20.0 and up (https://github.com/mendixlabs/list-view-controls#dependencies). This error does not occur with compatible Mendix versions. You could either upgrade your Mendix version, or downgrade to version 1.2.3 which is still available here: https://github.com/mendixlabs/list-view-controls/releases/tag/v1.2.3
